config/routes.rb
Rails.application.routes.draw do
  
  get 'cover_types/new'
  get 'cover_types/create'
  get 'cover_types/edit'
  get 'cover_types/update'
  get 'cover_types/index'
  get 'cover_types/show'
  get 'cover_types/destroy'

  get 'book_statuses/new'
  get 'book_statuses/create'
  get 'book_statuses/edit'
  get 'book_statuses/update'
  get 'book_statuses/index'
  get 'book_statuses/show'
  get 'book_statuses/destroy'

  get 'book_categories/new'
  get 'book_categories/create'
  get 'book_categories/edit'
  get 'book_categories/update'
  get 'book_categories/index'
  get 'book_categories/show'
  get 'book_categories/destroy'

  get 'book_languages/new'
  get 'book_languages/create'
  get 'book_languages/edit'
  get 'book_languages/update'
  get 'book_languages/index'
  get 'book_languages/show'
  get 'book_languages/destroy'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/index'
  get 'users/show'
  get 'users/destroy'

  get 'roles/new'
  get 'roles/create'
  get 'roles/edit'
  get 'roles/update'
  get 'roles/index'
  get 'roles/show'
  get 'roles/destroy'

  get 'dashboard/index'
  get 'dashboard/show'

  root 'sessions#new'
  

  get 'dang-nhap' => 'sessions#new', :as => 'dang-nhap'
  get 'dashboard' => 'dashboard#index', :as =>'dashboard-main'

  resources :dashboard, :roles, :users, :sessions, :book_languages, 
            :book_categories, :book_statuses, :cover_types

end

app/models/user.rb
class User < ActiveRecord::Base
    attr_accessor :password
    
    belongs_to :role
    
    email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
    
    validates :name,  :presence 	 => true,
			  :length			  	 => { :maximum => 50 }
	validates :email, :presence 	 => true,
	  		  :format			  	 => { :with => email_regex },
	  		  :uniqueness		  	 => { :case_sensitive => false }

	validates :password, :presence => true,
	  		  :length				 => { :within => 6..40 }
	  
	before_create :encrypting_password
	
	
	def has_password?(submitted_password)
  	  encrypt_password == encrypt(submitted_password)
    end

    def self.authenticate(email, submitted_password)
  	  user = User.find_by(email: email)
  	  return nil if user.nil?
  	  return user if user.has_password?(submitted_password)
    end

    private 
  	  def encrypting_password
  	  	#generate a unique salt if it is a new user
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?

  		# encrypt the password and store that in the encrypt_password field
  		self.encrypt_password = encrypt(password)
  	  end

  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end
end

#16f3e96bd933dbb40be0cf107125a8ac1261ca0336ab704a8cbf31b90146fcbf
#16f3e96bd933dbb40be0cf107125a8ac1261ca0336ab704a8cbf31b90146fcbf

#5cbfd7ce45868ca3abe4f908daa238dcaf9b880a6fa177f9a83286de1d40460c

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :verify_logged
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
    @user.provider = "Website"
    @user.created_by = "Admin"
    @user.updated_by = "Admin"
    @user.delete_flag = 0

  	if @user.save
  		redirect_to users_path, notice: 'User was save successfull created'
  	else
  		render action: 'new'
  	end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    byebug
    @user = User.find(params[:id])
     
     if @role.update(:updated_at => DateTime.now, :name => role_params[:name], :description => role_params[:description])
         flash[:success] = 'Cập nhật Role Thành Công'
         redirect_to roles_path
     else
       render 'new'
     end
  end
  
  def index
    @users = User.where(delete_flag: 0).all
  end
  
  def show
  	@user = User.find(params[:id])
  end

  private 
  def user_params
      params.require(:user).permit(:name, :email, :password, :provider, :role_id, :delete_flag, :created_by, :updated_by)
  end
end

app/views/users/index.html.erb
<section class="content-header">
  <h1>
    User Management
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">List Users</h3>

              <div class="box-tools">
                <%= link_to "Add new", users_new_path, class: 'btn btn-success' %>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
            <% if @users.size > 0 %>
              <table class="table table-hover">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th>Provider</th>
                  <th>Created at</th>
                  <th>Created by</th>
                  <th>Action</th>
                </tr>
                <% @users.each do |f| %>
                  <tr>
                  <td><%= f.id %></td>
                  <td><%= f.name %></td>
                  <td><%= f.email %></td>
                  <td><%= f.role.name %></td>
                  <td><%= f.provider %></td>
                  <td><%= f.created_at %></td>
                  <td><%= f.created_by %></td>
                  <td><%= link_to 'Edit', edit_user_path(f), class:'btn btn-primary' %><%= link_to 'Delete', user_path(f), class:'btn btn-danger', method: :delete, data: {confirm: 'Bạn có muốn xóa Tài Khoản này không ?'} %></td>
                </tr>  
                <% end %>
              </table>
             <% else %>
                 <p>Chưa có tài khoản nào</p>
             <% end %>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
</section>

app/views/users/new.html.erb
<section class="content-header">
  <h1>
    User Management
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Add new User</h3>
            </div>
            <!-- /.box-header -->
            <%= form_for @user, :html => {class: 'form-horizontal '} do |f| %>
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-10">
                            <%= f.text_field :name, class:'form-control', placeholder:'Name', id: 'inputEmail', required:'required' %>
                          </div>
                    </div>
                    <div class="form-group">
                      <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                
                      <div class="col-sm-10">
                        <%= f.password_field :password, class:'form-control', placeholder:'Password', id: 'inputDescription', required:'required' %>
                      </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <%= f.text_field :email, class:'form-control', placeholder:'Email', id: 'inputEmail', required:'required' %>
                          </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Role</label>
                        <div class="col-sm-10">
                            <%= f.select :role_id, Role.all.collect {|r| [r.name, r.id]}, {:include_blank => '-- Chọn Quyền --'}, class: 'form-control' %>
                          </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <%= link_to "Cancel", roles_path, class:'btn btn-default' %>
                    <%= f.submit "Create", class:'btn btn-info pull-right' %>
                </div>
            <!-- /.box-footer -->
            <% end %>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
    </div>
</section>