config/routes.rb
Rails.application.routes.draw do
  
  get 'cover_types/new'
  get 'cover_types/create'
  get 'cover_types/edit'
  get 'cover_types/update'
  get 'cover_types/index'
  get 'cover_types/show'
  get 'cover_types/destroy'

  get 'book_statuses/new'
  get 'book_statuses/create'
  get 'book_statuses/edit'
  get 'book_statuses/update'
  get 'book_statuses/index'
  get 'book_statuses/show'
  get 'book_statuses/destroy'

  get 'book_categories/new'
  get 'book_categories/create'
  get 'book_categories/edit'
  get 'book_categories/update'
  get 'book_categories/index'
  get 'book_categories/show'
  get 'book_categories/destroy'

  get 'book_languages/new'
  get 'book_languages/create'
  get 'book_languages/edit'
  get 'book_languages/update'
  get 'book_languages/index'
  get 'book_languages/show'
  get 'book_languages/destroy'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/index'
  get 'users/show'
  get 'users/destroy'

  get 'roles/new'
  get 'roles/create'
  get 'roles/edit'
  get 'roles/update'
  get 'roles/index'
  get 'roles/show'
  get 'roles/destroy'

  get 'dashboard/index'
  get 'dashboard/show'

  root 'sessions#new'
  

  get 'dang-nhap' => 'sessions#new', :as => 'dang-nhap'
  get 'dashboard' => 'dashboard#index', :as =>'dashboard-main'

  resources :dashboard, :roles, :users, :sessions, :book_languages, 
            :book_categories, :book_statuses, :cover_types

end

app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :verify_logged
  
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)
    if @role.save
      redirect_to roles_path, notice: 'Role was save successfull created'
    else
      render 'new'
    end
  end

  def edit
    @role = Role.find(params[:id])
  end

  def update
     @role = Role.find(params[:id])
     
     if @role.update(:updated_at => DateTime.now, :name => role_params[:name], :description => role_params[:description])
         flash[:success] = 'Cập nhật Role Thành Công'
         redirect_to roles_path
     else
       render 'new'
     end
  end

  def index
    @roles = Role.all.order('Id ASC')
  end

  def show
  end

  def destroy
  end
  
  private
    def role_params
      params.require(:role).permit(:name, :description)
    end
end

app/helpers/role_helper.rb
module RoleHelper
end

app/views/roles/destroy.html.erb
<h1>Role#destroy</h1>
<p>Find me in app/views/role/destroy.html.erb</p>

app/views/roles/edit.html.erb
<div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">Edit Role</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <%= form_for @role, :html => {class: 'form-horizontal '} do |f| %>
        <div class="box-body">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <%= f.text_field :name, class:'form-control', placeholder:'Name', id: 'inputEmail', required:'required' %>
                  </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
        
              <div class="col-sm-10">
                <%= f.text_field :description, class:'form-control', placeholder:'Description', id: 'inputDescription', required:'required' %>
              </div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <%= link_to "Cancel", roles_path, class:'btn btn-default' %>
            <%= f.submit "Update", class:'btn btn-info pull-right' %>
        </div>
        <!-- /.box-footer -->
    <% end %>

app/views/roles/index.html.erb
<section class="content-header">
  <h1>
    Role Management
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">List Role</h3>

              <div class="box-tools">
                <%= link_to "Add new", roles_new_path, class: 'btn btn-success' %>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Action</th>
                </tr>
                <% @roles.each do |f| %>
                  <tr>
                  <td><%= f.id %></td>
                  <td><%= f.name %></td>
                  <td><%= f.description %></td>
                  <td><%= link_to 'Edit', edit_role_path(f), class:'btn btn-primary' %><%= link_to 'Delete', role_path(f), class:'btn btn-danger', method: :delete, data: {confirm: 'Bạn có muốn xóa Quyền này không ?'} %></td>
                </tr>  
                <% end %>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
</section>

app/views/roles/new.html.erb
<div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">Add new Role</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <%= form_for @role, :html => {class: 'form-horizontal '} do |f| %>
        <div class="box-body">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                <div class="col-sm-10">
                    <%= f.text_field :name, class:'form-control', placeholder:'Name', id: 'inputEmail', required:'required' %>
                  </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
        
              <div class="col-sm-10">
                <%= f.text_field :description, class:'form-control', placeholder:'Description', id: 'inputDescription', required:'required' %>
              </div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <%= link_to "Cancel", roles_path, class:'btn btn-default' %>
            <%= f.submit "Create", class:'btn btn-info pull-right' %>
        </div>
        <!-- /.box-footer -->
    <% end %>
</div>

app/views/roles/show.html.erb
<h1>Role#show</h1>
<p>Find me in app/views/role/show.html.erb</p>

app/views/roles/update.html.erb
<h1>Role#update</h1>
<p>Find me in app/views/role/update.html.erb</p>