config/routes.rb
Rails.application.routes.draw do
  
  get 'cover_types/new'
  get 'cover_types/create'
  get 'cover_types/edit'
  get 'cover_types/update'
  get 'cover_types/index'
  get 'cover_types/show'
  get 'cover_types/destroy'

  get 'book_statuses/new'
  get 'book_statuses/create'
  get 'book_statuses/edit'
  get 'book_statuses/update'
  get 'book_statuses/index'
  get 'book_statuses/show'
  get 'book_statuses/destroy'

  get 'book_categories/new'
  get 'book_categories/create'
  get 'book_categories/edit'
  get 'book_categories/update'
  get 'book_categories/index'
  get 'book_categories/show'
  get 'book_categories/destroy'

  get 'book_languages/new'
  get 'book_languages/create'
  get 'book_languages/edit'
  get 'book_languages/update'
  get 'book_languages/index'
  get 'book_languages/show'
  get 'book_languages/destroy'

  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/index'
  get 'users/show'
  get 'users/destroy'

  get 'roles/new'
  get 'roles/create'
  get 'roles/edit'
  get 'roles/update'
  get 'roles/index'
  get 'roles/show'
  get 'roles/destroy'

  get 'dashboard/index'
  get 'dashboard/show'

  root 'sessions#new'
  

  get 'dang-nhap' => 'sessions#new', :as => 'dang-nhap'
  get 'dashboard' => 'dashboard#index', :as =>'dashboard-main'

  resources :dashboard, :roles, :users, :sessions, :book_languages, 
            :book_categories, :book_statuses, :cover_types

end

app/controllers/book_statuses_controller.rb
class BookStatusesController < ApplicationController
  before_filter :verify_logged
  
  def new
     @book_status = BookStatus.new
  end

  def create
    @user = User.find(params[:user_id])
    @book_status = BookStatus.new(status_params)
    @book_status.delete_flag = 0
    @book_status.created_by = @user.name
    @book_status.updated_by = @user.name
    
    if @book_status.save
      redirect_to book_statuses_path, notice: 'Book Status was save successfull created'
    else
      render 'new'
    end
    
  end

  def edit
  end

  def update
  end

  def index
    @bstatuses = BookStatus.where(delete_flag: 0).all
  end

  def show
  end

  def destroy
  end
  
  private
    def status_params
      params.require(:book_status).permit(:name, :description, :delete_flag, :created_by, :updated_by, :slug)
    end
end

app/views/book_statuses/index.html.erb
<section class="content-header">
  <h1>
    Book Statuses Management
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">List Book Statuses</h3>

              <div class="box-tools">
                <%= link_to "Add new", book_statuses_new_path, class: 'btn btn-success' %>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
            <% if @bstatuses.size > 0 %>
              <table class="table table-hover">
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Created at</th>
                  <th>Created by</th>
                  <th>Action</th>
                </tr>
                <% @bstatuses.each do |f| %>
                  <tr>
                  <td><%= f.id %></td>
                  <td><%= f.name %></td>
                  <td><%= f.description %></td>
                  <td><%= f.created_at %></td>
                  <td><%= f.created_by %></td>
                  <td><%= link_to 'Edit', edit_book_status_path(f), class:'btn btn-primary' %><%= link_to 'Delete', book_status_path(f), class:'btn btn-danger', method: :delete, data: {confirm: 'Bạn có muốn xóa Item này không ?'} %></td>
                </tr>  
                <% end %>
              </table>
             <% else %>
                 <p>Chưa có danh mục nào</p>
             <% end %>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
</section>

app/views/book_statuses/new.html.erb
<section class="content-header">
  <h1>
    Book Statuses Management
    <small>List</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
  </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Add new Status</h3>
            </div>
            <!-- /.box-header -->
            <%= form_for @book_status, :html => {class: 'form-horizontal '} do |f| %>
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-10">
                            <%= f.text_field :name, class:'form-control', placeholder:'Name', id: 'inputEmail', required:'required' %>
                          </div>
                    </div>
                    <div class="form-group">
                      <label for="inputPassword3" class="col-sm-2 control-label">Description</label>
                
                      <div class="col-sm-10">
                        <%= f.text_field :description, class:'form-control', placeholder:'Description', id: 'inputDescription', required:'required' %>
                      </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <%= link_to "Cancel", book_statuses_path, class:'btn btn-default' %>
                    <%= f.submit "Create", class:'btn btn-info pull-right' %>
                </div>
            <!-- /.box-footer -->
            <% end %>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
    </div>
</section>